web/router.ex
defmodule Pxblog.Router do
  use Pxblog.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Pxblog do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController do
      resources "/posts", PostController
    end

    resources "/posts", PostController, only: [] do
      resources "/comments", CommentController,
        only: [:create, :delete, :update]
    end

    resources "/sessions", SessionController,
      only: [:new, :create, :delete]
  end

  # Other scopes may use custom stacks.
  # scope "/api", Pxblog do
  #   pipe_through :api
  # end
end

web/models/comment.ex
defmodule Pxblog.Comment do
  use Pxblog.Web, :model

  schema "comments" do
    field :author, :string
    field :body, :string
    field :approved, :boolean, default: false
    belongs_to :post, Pxblog.Post

    timestamps
  end

  @required_fields ~w(author body approved)
  @optional_fields ~w()

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
  end
end

web/controllers/comment_controller.ex
defmodule Pxblog.CommentController do
  use Pxblog.Web, :controller

  alias Pxblog.Comment
  alias Pxblog.Post

  plug :scrub_params, "comment" when action in [:create, :update]
  plug :set_post_and_authorize_user when action in [:update, :delete]

  def create(conn, %{"comment" => comment_params, "post_id" => post_id}) do
    post = Repo.get!(Post, post_id)
      |> Repo.preload([:user, :comments])
    changeset = post
      |> build_assoc(:comments)
      |> Comment.changeset(comment_params)

    case Repo.insert(changeset) do
      {:ok, _comment} ->
        conn
          |> put_flash(:info, "Comment created successfully!")
          |> redirect(to: user_post_path(conn, :show, post.user, post))
      {:error, changeset} ->
        render(conn, Pxblog.PostView, "show.html",
          post: post, user: post.user, comment_changeset: changeset)
    end
  end

  def update(conn, %{"id" => id, "post_id" => post_id, "comment" => comment_params}) do
    post = Repo.get!(Post, post_id) |> Repo.preload(:user)
    comment = Repo.get! Comment, id
    changeset = Comment.changeset comment, comment_params

    case Repo.update(changeset) do
      {:ok, _} ->
        conn
          |> put_flash(:info, "Comment updated successfully.")
          |> redirect(to: user_post_path(conn, :show, post.user, post))
      {:error, _} ->
        conn
          |> put_flash(:info, "Failed to update comment!")
          |> redirect(to: user_post_path(conn, :show, post.user, post))
    end
  end

  def delete(conn, %{"id" => id, "post_id" => post_id}) do
    post = Repo.get!(Post, post_id) |> Repo.preload(:user)
    Repo.get!(Comment, id) |> Repo.delete!

    conn
     |> put_flash(:info, "Deleted comment!")
     |> redirect(to: user_post_path(conn, :show, post.user, post))
  end

  defp set_post(conn) do
    post = Repo.get!(Post, conn.params["post_id"])
      |> Repo.preload(:user)
    assign(conn, :post, post)
  end

  defp set_post_and_authorize_user(conn, _opts) do
    conn = set_post conn

    if is_authorized_user?(conn) do
      conn
    else
      conn
        |> put_flash(:error, "You are not authorized to modify that comment!")
        |> redirect(to: page_path(conn, :index))
        |> halt
    end
  end

  defp is_authorized_user?(conn) do
    user = get_session conn, :current_user
    post = conn.assigns[:post]
    (user && (user.id == post.user_id ||
      Pxblog.RoleChecker.is_admin?(user)))
  end
end

web/views/comment_view.ex
defmodule Pxblog.CommentView do
  use Pxblog.Web, :view
end

web/templates/comment/comment.html.eex
<%= if @conn.assigns[:author_or_admin] || @comment.approved do %>
<div class="comment">
  <div class="row">
    <div class="col-xs-4">
      <strong><%= @comment.author %></strong>
    </div>
    <div class="col-xs-4">
      <em><%= @comment.inserted_at %></em>
    </div>
    <div class="col-xs-4 text-right">
      <%= if @conn.assigns[:author_or_admin] do %>
        <%= unless @comment.approved do %>
          <%= form_for @conn, post_comment_path(@conn, :update, @post, @comment), [method: :put, name: :comment, style: "display: inline;"], fn f -> %>
            <%= hidden_input f, :approved, value: "true" %>
            <%= submit "Approve", class: "btn btn-xs btn-primary approve" %>
          <% end %>
        <% end %>
        <%= link "Delete",
              method: :delete,
              to: post_comment_path(@conn, :delete, @post, @comment),
              class: "btn btn-xs btn-danger delete",
              data: [confirm: "Are you sure you want to delete this comment?"]
        %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12">
      <%= @comment.body %>
    </div>
  </div>
</div>
<% end %>

web/templates/comment/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :author, class: "control-label" %>
    <%= text_input f, :author, class: "form-control" %>
    <%= error_tag f, :author %>
  </div>

  <div class="form-group">
    <%= label f, :body, class: "control-label" %>
    <%= textarea f, :body, class: "form-control", id: "body-editor" %>
    <%= error_tag f, :body %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>